// <auto-generated />
using System;
using LEARNING_.NET_API_ANGULAR.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LEARNING_.NET_API_ANGULAR.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LEARNING_.NET_API_ANGULAR.FastfoodStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bread")
                        .HasColumnType("int");

                    b.Property<int>("Cheese")
                        .HasColumnType("int");

                    b.Property<int>("Coke")
                        .HasColumnType("int");

                    b.Property<int>("Ketchup")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastRestock")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Lettuce")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Mayonnaise")
                        .HasColumnType("int");

                    b.Property<int>("Meat")
                        .HasColumnType("int");

                    b.Property<int>("Mustard")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Onion")
                        .HasColumnType("int");

                    b.Property<int>("Pickle")
                        .HasColumnType("int");

                    b.Property<int>("Potato")
                        .HasColumnType("int");

                    b.Property<int>("Tomato")
                        .HasColumnType("int");

                    b.Property<int>("Water")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FastfoodStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
